#!/bin/bash

scp acer64debian:cvs/release .
export VERSION=`cat release`
scp acer64debian:cvs/cvsnt-$VERSION.tar.gz .
rm -rf ./cvsnt-$VERSION.tar
rm -rf ./cvsnt-$VERSION
gunzip ./cvsnt-$VERSION.tar.gz
tar xf ./cvsnt-$VERSION.tar
export CVSNT=${PWD}/cvsnt-$VERSION

export PREFIX=/usr/local
export CONFIG=/etc/cvsnt
export DESTDIR=${PWD}/tmp
export MYSQLDIR=${PWD}/../um_mysql64
rm -rf $DESTDIR
mkdir $DESTDIR
export LD_LIBRARY_PATH=${DESTDIR}${PREFIX}/lib/sparcv9:/usr/local/lib/sparcv9:/usr/local/ssl/lib/sparcv9
cd $CVSNT
make distclean
./configure --prefix=$PREFIX --with-config-dir=$CONFIG --with-ssl=/usr/local/ssl --libdir=$PREFIX/lib/sparcv9 --bindir=$PREFIX/bin/sparcv9 CFLAGS="-m64 -O2 -fPIC" CXXFLAGS="-m64 -O2 -fPIC" CPPFLAGS="-I/usr/local/include -I$MYSQLDIR/include/mysql" LDFLAGS="-L/usr/local/sparcv9/lib -L$PREFIX/lib/sparcv9 -R$PREFIX/lib/sparcv9 -L$MYSQLDIR/lib/sparcv9" 
make DESTDIR=${DESTDIR}
make install DESTDIR=${DESTDIR}
if [ ! -x ${DESTDIR}${PREFIX}/bin/sparcv9/cvsnt ]; then echo "cvsnt not executable at ${DESTDIR}${PREFIX}/bin/sparcv9/cvsnt"; exit 1; fi

cd ${DESTDIR}
export LD_LIBRARY_PATH_64=${DESTDIR}${PREFIX}/lib/sparcv9:/usr/local/lib/sparcv9:/usr/local/ssl/lib/sparcv9
BUILD=`${DESTDIR}${PREFIX}/bin/sparcv9/cvsnt version -q`
if [ ! -n "$BUILD" ]; then echo "cannot get build number from ${DESTDIR}${PREFIX}/bin/sparcv9/cvsnt version -q"; exit 1; fi
cp ../postinstall .
echo ../make_package 64 ${BUILD} cvsnt
../make_package 64 ${BUILD} cvsnt
cd ..
if [ -f cvsnt-${BUILD}-sol9-sparc64.bz2 ]; then  scp cvsnt-${BUILD}-sol9-sparc64.bz2 acer64debian:cvs ; fi
echo "Built: cvsnt-${BUILD}-sol9-sparc64.bz2"

